### ISSUE TITLE
.pl matches non-Perl files

### ISSUE THREAD

**Issue by nanis** [anvaka/common-words#3]
See, for example, [11-Rest_SlumpOnFloor/rsfgtMovementIndv_new.pl][1]. This means a lot of non-Perl gets indexed as Perl.

Also, Perl code also comes in `.pm`, `.plx`, and `.t` files as well as files with no extension. Any file with `perl` in the shebang line is likely a Perl script, and any file that has `package` statements is likely to be a Perl module.

Ignoring all those and focusing solely on `.pl` extensions results in oddities such as [this][2].

[1]: https://github.com/JasonFil/Prob-EC/blob/c6b1a8d4aaf82e7b44efb3329d425cdbf92e0f31/dataset/strong-noise/11-Rest_SlumpOnFloor/rsfgtMovementIndv_new.pl

[2]: https://www.reddit.com/r/programming/comments/5opk2f/i_analyzed_2tb_of_code_to_build_an_index_of_the/dclk6ph/

**Comment by anvaka** [comment]
As someone [suggested on reddit](https://www.reddit.com/r/perl/comments/5orywn/i_analyzed_2tb_of_code_to_build_an_index_of_the/dcm0x9m/) I changed perl visualization to include only `pm` files. Please let me know how you feel about new version?

**Comment by nanis** [comment]
That cloud looks more reasonable. Although it looks like it is also capturing Perl 6 content as indicated by the prominence of `nqp`.
