### ISSUE TITLE
Export SVG?...

### ISSUE THREAD

**Issue by ashald** [anvaka/common-words#6]
Amazing work! Thank you!

I enjoy it so much that I'd like to make a print for some languages and put it on the walls in my apartments. You mentioned that word clouds are rendered as SVG so it sounds like it's possible to print it in arbitrary size. Is there is a way to export the SVG from the page?

**Comment by anvaka** [comment]
Added a function to export svg. Open developer console and type

```
exportSVG()
```

It should save the file:
![export_svg](https://cloud.githubusercontent.com/assets/225407/22343056/826539ee-e3ab-11e6-9837-0a896de99910.gif)

You can also pass the dimensions of the SVG if you wish:

```
exportSVG(2048, 2048)
```

**Comment by ashald** [comment]
**HUGE** thanks! 👍
