### ISSUE TITLE
Can I print these clouds for my cube

### ISSUE THREAD

**Issue by crdesai** [anvaka/common-words#8]
I love these language clouds and would love to print one to be posted in my cube. I tried printing it from the website but the standard "Ctrl+P" only gets half of the image. Is there a better way to print the image for the word cloud?

**Comment by anvaka** [comment]
Sure!

I added a function to export svg. Open developer console and type

```
exportSVG()
```

It should save the file:
![export_svg](https://cloud.githubusercontent.com/assets/225407/22343056/826539ee-e3ab-11e6-9837-0a896de99910.gif)

You can also pass the dimensions of the SVG if you wish:

```
exportSVG(2048, 2048)
```
